'use client';

import { useState } from 'react';
import Header from '../../components/navigation/header';
import ChatDrawer from '../../components/ai/chat-drawer';
import { FileText, Sparkles, Calendar } from 'lucide-react';

export default function ReportsPage() {
  const [isAIChatOpen, setIsAIChatOpen] = useState(false);

  return (
    <div className="flex-1 flex flex-col min-w-0 bg-slate-950 text-slate-100 min-h-screen">
      <Header onOpenAIChat={() => setIsAIChatOpen(true)} />

      <main className="flex-1 p-6 space-y-6 max-w-7xl w-full mx-auto">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2">
            <FileText className="w-6 h-6 text-purple-400" /> Engineering Management Reports
          </h1>
          <p className="text-slate-400 text-xs mt-1">
            Automated EOD, Weekly, and Monthly engineering summaries generated by Gemini.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {['EOD Executive Summary', 'Weekly Engineering Digest', 'Monthly Project Performance'].map((title, idx) => (
            <div key={idx} className="bg-slate-900/70 border border-slate-800 p-5 rounded-2xl space-y-3">
              <div className="flex items-center space-x-2 text-purple-400">
                <Sparkles className="w-4 h-4" />
                <h3 className="font-semibold text-white text-sm">{title}</h3>
              </div>
              <p className="text-xs text-slate-400">
                Generates a factual report synthesizing commits, PRs, review throughput, and developer activity.
              </p>
              <button
                onClick={() => setIsAIChatOpen(true)}
                className="w-full py-2 bg-purple-600/20 hover:bg-purple-600/30 text-purple-300 border border-purple-500/30 rounded-xl text-xs font-medium transition-colors"
              >
                Generate Report via AI
              </button>
            </div>
          ))}
        </div>
      </main>

      <ChatDrawer isOpen={isAIChatOpen} onClose={() => setIsAIChatOpen(false)} />
    </div>
  );
}
