"""
Response Generation Schemas & Structured Envelopes for Engineering AI Agent.
Enforces strict factual grounding, anti-hallucination metadata, and provenance tracking.
"""
from enum import Enum
from typing import Optional, Dict, Any, List, Union
from datetime import datetime, timezone
from pydantic import BaseModel, Field


class DataAvailabilityStatus(str, Enum):
    """Data availability classification for the synthesized answer."""
    AVAILABLE = "available"        # Telemetry contains positive factual records
    EMPTY = "empty"                # No records found matching query criteria (zero-fabrication enforced)
    CONFLICTING = "conflicting"    # Discrepancy observed across different tool streams / caches
    ERROR = "error"                # Telemetry retrieval encountered non-recoverable error


class MetricItem(BaseModel):
    """Individual numerical KPI or metric extracted from factual telemetry."""
    name: str = Field(..., description="Metric name (e.g., 'Total Commits', 'PR Velocity')")
    value: Union[int, float, str] = Field(..., description="Factual value")
    unit: Optional[str] = Field(None, description="Optional unit (e.g. 'commits', 'lines', 'hours')")
    context: Optional[str] = Field(None, description="Additional context or time window")


class FactCheckedResponse(BaseModel):
    """
    Complete structured response generated by the Response Generation stage.
    Ensures zero-fabrication, verified entity lists, and clean presentation.
    """
    summary: str = Field(..., description="Concise direct answer to the user prompt")
    markdown_content: str = Field(..., description="Full synthesized technical answer in GitHub-flavored Markdown")
    data_availability: DataAvailabilityStatus = Field(DataAvailabilityStatus.AVAILABLE, description="Availability state of underlying telemetry")
    key_metrics: List[MetricItem] = Field(default_factory=list, description="Factual numbers and KPIs mentioned")
    entities_involved: Dict[str, List[str]] = Field(default_factory=dict, description="Categorized list of verified entities (repositories, developers, projects)")
    time_period: Optional[str] = Field(None, description="Timeframe considered (e.g. 'today', 'last 30 days', 'historical')")
    grounding_sources: List[str] = Field(default_factory=list, description="Tools or endpoints providing factual grounding")
    actions: List[Dict[str, str]] = Field(default_factory=list, description="Interactive quick-links or follow-up actions")
    freshness_tier: Optional[str] = Field(None, description="Freshness tier (historical, recent_sync, live_current)")
    as_of: str = Field(default_factory=lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"))
