"""
Data Models and Enums for the Future RAG Architecture Foundation.
Defines strict Knowledge Source provenances, document structures, chunks, and retrieval bundles.
"""
import uuid
import time
from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class KnowledgeSourceType(str, Enum):
    """
    Categorical taxonomy of distinct knowledge sources.
    The Engineering Agent must NEVER mix or confuse these sources.
    """
    GITHUB_APPLICATION_DATA = "github_application_data"  # Telemetry, commits, PRs, issues, developers, metrics (Tool Layer)
    COMPANY_KNOWLEDGE = "company_knowledge"              # Internal tenant documentation, runbooks, architecture ADRs, SOPs (Tenant RAG)
    GENERAL_IT_KNOWLEDGE = "general_it_knowledge"        # General software engineering standards, patterns, language syntax (Global RAG/Docs)
    LLM_PARAMETRIC_KNOWLEDGE = "llm_parametric_knowledge" # Base LLM pre-trained reasoning capabilities without external grounding


class DocumentType(str, Enum):
    """Supported format classifications for incoming knowledge documents."""
    MARKDOWN = "markdown"
    PLAINTEXT = "plaintext"
    CODE_FILE = "code_file"
    OPENAPI_SPEC = "openapi_spec"
    PDF = "pdf"
    JSON_SCHEMA = "json_schema"


class DocumentMetadata(BaseModel):
    """Metadata describing the origin, tenant ownership, and tags of a knowledge document."""
    tenant_id: Optional[str] = Field(None, description="Tenant/organization ownership ID (required for company knowledge)")
    document_id: str = Field(default_factory=lambda: f"doc-{uuid.uuid4().hex[:12]}")
    title: str = Field(..., description="Document title or file path")
    source_type: KnowledgeSourceType = Field(..., description="Provenance category")
    doc_type: DocumentType = Field(DocumentType.MARKDOWN, description="Format type")
    source_url: Optional[str] = None
    author: Optional[str] = None
    version: Optional[str] = "1.0"
    created_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)
    tags: List[str] = Field(default_factory=list)
    custom_attributes: Dict[str, Any] = Field(default_factory=dict)


class KnowledgeDocument(BaseModel):
    """Unprocessed or pre-processed full knowledge document."""
    metadata: DocumentMetadata
    raw_content: str = Field(..., description="Full text or serialized content of the document")
    cleaned_content: Optional[str] = None


class DocumentChunk(BaseModel):
    """Granular chunk of a document generated by a chunking strategy."""
    chunk_id: str = Field(default_factory=lambda: f"chk-{uuid.uuid4().hex[:12]}")
    document_id: str
    tenant_id: Optional[str] = None
    source_type: KnowledgeSourceType
    chunk_index: int = 0
    title: str
    content: str
    token_count: int = 0
    embedding: Optional[List[float]] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class RetrievalQuery(BaseModel):
    """Parameters passed to vector store and knowledge retriever."""
    query_text: str
    tenant_id: Optional[str] = Field(None, description="Tenant scope for company knowledge")
    source_types: List[KnowledgeSourceType] = Field(
        default_factory=lambda: [KnowledgeSourceType.COMPANY_KNOWLEDGE, KnowledgeSourceType.GENERAL_IT_KNOWLEDGE]
    )
    top_k: int = 3
    similarity_threshold: float = 0.65
    filter_tags: List[str] = Field(default_factory=list)


class RetrievedChunkItem(BaseModel):
    """Individual chunk matched and returned by the retriever."""
    chunk: DocumentChunk
    similarity_score: float
    rank: int = 1


class GroundedContextBundle(BaseModel):
    """Packaged contextual block formatted for injection into the Engineering Agent StateGraph."""
    source_type: KnowledgeSourceType
    matched_chunks: List[RetrievedChunkItem] = Field(default_factory=list)
    formatted_context: str = ""
    is_grounded: bool = False
    citation_references: List[str] = Field(default_factory=list)
