"""
Response Schemas for Engineering AI Agent.
"""
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field

class MetricItem(BaseModel):
    """Structured KPI or telemetry metric computed by the agent."""
    label: str = Field(..., description="Display title for metric")
    value: Any = Field(..., description="Numeric or string metric value")
    change: Optional[str] = Field(None, description="Percentage or relative delta")
    color: Optional[str] = Field("emerald", description="UI badge accent color")

class ArtifactItem(BaseModel):
    """Structured artifact generated by the agent (e.g. Markdown report, JSON table, CSV export)."""
    id: str = Field(..., description="Unique artifact identifier")
    title: str = Field(..., description="Artifact title")
    artifact_type: str = Field(..., description="Type: report, table, chart_data, diff_summary")
    content: str = Field(..., description="Artifact markdown or serialized content")
    created_at: str = Field(..., description="ISO timestamp")

class ActionItem(BaseModel):
    """Actionable recommendation or deep link suggested by the agent."""
    label: str = Field(..., description="Action button text")
    href: Optional[str] = Field(None, description="Navigation target URL or route")
    action_type: Optional[str] = Field("link", description="Type: link, command, modal")

class ToolExecutionSummary(BaseModel):
    """Public summary of a tool execution (without exposing raw internal secrets)."""
    tool_name: str = Field(..., description="Name of executed tool")
    status: str = Field(..., description="Success or error status")
    duration_ms: float = Field(..., description="Execution time in milliseconds")
    start_time: Optional[float] = Field(None, description="Tool start epoch timestamp")
    end_time: Optional[float] = Field(None, description="Tool end epoch timestamp")
    error: Optional[str] = Field(None, description="Error message if tool execution failed")

import uuid

class ExecutionTelemetryTrace(BaseModel):
    """Internal execution telemetry trace safely captured for every Engineering Agent request (Phase 25K & Part 6)."""
    request_id: Optional[str] = Field(default_factory=lambda: f"req-{uuid.uuid4().hex[:12]}", description="Unique request identifier")
    trace_id: Optional[str] = Field(default_factory=lambda: f"trace-{uuid.uuid4().hex[:16]}", description="Unique trace identifier alias")
    query: Optional[str] = Field(None, description="User query prompt")
    intent: Optional[str] = Field(None, description="Detected intent category")
    route: Optional[str] = Field(None, description="Execution route: direct_llm, tool_first, multi_agent, etc.")
    llm_provider: str = Field(..., description="LLM provider name")
    llm_model: str = Field(..., description="LLM model name")
    llm_called: bool = Field(True, description="Whether an LLM endpoint was called")
    llm_latency_ms: float = Field(0.0, description="LLM invocation latency in milliseconds")
    tools_selected: List[str] = Field(default_factory=list, description="List of tools selected for execution")
    tools_executed: List[str] = Field(default_factory=list, description="List of tool names executed")
    tools_called: List[Dict[str, Any]] = Field(default_factory=list, description="Safe summary of tool calls")
    tool_latency_ms: float = Field(0.0, description="Sum or aggregate tool execution duration in ms")
    database_latency_ms: float = Field(0.0, description="Database / cache retrieval duration in ms")
    total_latency_ms: float = Field(0.0, description="Total request processing latency in ms")
    success: bool = Field(True, description="Whether the request succeeded")
    error_type: Optional[str] = Field(None, description="Type or category of error if failed")
    response_generation: Dict[str, Any] = Field(default_factory=dict, description="Response generation step metrics")



class EngineeringAgentResponse(BaseModel):
    """Main response envelope returned by the Engineering AI Agent."""
    success: bool = Field(True, description="Indicates whether the agent executed successfully")
    conversation_id: str = Field(..., description="Session/conversation identifier")
    message_id: str = Field(..., description="Unique response message identifier")
    response: str = Field(..., description="Synthesized engineering insights & response")
    detected_intent: Optional[str] = Field(None, description="High-level engineering category identified")
    selected_agent: Optional[str] = Field(None, description="Specialized sub-agent that handled execution")
    metrics: List[MetricItem] = Field(default_factory=list, description="Computed metrics and KPIs")
    artifacts: List[ArtifactItem] = Field(default_factory=list, description="Generated analytical artifacts or reports")
    actions: List[ActionItem] = Field(default_factory=list, description="Recommended next actions")
    tools_executed: List[ToolExecutionSummary] = Field(default_factory=list, description="Public summary of tools used")
    execution_time_ms: float = Field(0.0, description="Total agent execution duration in milliseconds")
    llm_diagnostics: Optional[Dict[str, Any]] = Field(None, description="Safe LLM runtime execution diagnostics")
    execution_telemetry: Optional[ExecutionTelemetryTrace] = Field(None, description="Safe internal execution telemetry trace (Phase 25K)")
    error: Optional[str] = Field(None, description="Error message if execution encountered a failure")
