"""
Response Schemas for Engineering AI Agent.
"""
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field

class MetricItem(BaseModel):
    """Structured KPI or telemetry metric computed by the agent."""
    label: str = Field(..., description="Display title for metric")
    value: Any = Field(..., description="Numeric or string metric value")
    change: Optional[str] = Field(None, description="Percentage or relative delta")
    color: Optional[str] = Field("emerald", description="UI badge accent color")

class ArtifactItem(BaseModel):
    """Structured artifact generated by the agent (e.g. Markdown report, JSON table, CSV export)."""
    id: str = Field(..., description="Unique artifact identifier")
    title: str = Field(..., description="Artifact title")
    artifact_type: str = Field(..., description="Type: report, table, chart_data, diff_summary")
    content: str = Field(..., description="Artifact markdown or serialized content")
    created_at: str = Field(..., description="ISO timestamp")

class ActionItem(BaseModel):
    """Actionable recommendation or deep link suggested by the agent."""
    label: str = Field(..., description="Action button text")
    href: Optional[str] = Field(None, description="Navigation target URL or route")
    action_type: Optional[str] = Field("link", description="Type: link, command, modal")

class ToolExecutionSummary(BaseModel):
    """Public summary of a tool execution (without exposing raw internal secrets)."""
    tool_name: str = Field(..., description="Name of executed tool")
    status: str = Field(..., description="Success or error status")
    duration_ms: float = Field(..., description="Execution time in milliseconds")

class EngineeringAgentResponse(BaseModel):
    """Main response envelope returned by the Engineering AI Agent."""
    success: bool = Field(True, description="Indicates whether the agent executed successfully")
    conversation_id: str = Field(..., description="Session/conversation identifier")
    message_id: str = Field(..., description="Unique response message identifier")
    response: str = Field(..., description="Synthesized engineering insights & response")
    detected_intent: Optional[str] = Field(None, description="High-level engineering category identified")
    selected_agent: Optional[str] = Field(None, description="Specialized sub-agent that handled execution")
    metrics: List[MetricItem] = Field(default_factory=list, description="Computed metrics and KPIs")
    artifacts: List[ArtifactItem] = Field(default_factory=list, description="Generated analytical artifacts or reports")
    actions: List[ActionItem] = Field(default_factory=list, description="Recommended next actions")
    tools_executed: List[ToolExecutionSummary] = Field(default_factory=list, description="Public summary of tools used")
    execution_time_ms: float = Field(0.0, description="Total agent execution duration in milliseconds")
    error: Optional[str] = Field(None, description="Error message if execution encountered a failure")
